---
- name: "Setup backend app directory"
  become: true
  tasks:
    - name: "Copy build artifact to same directory as ansible deploy role"
      copy:
        src: ../../../../../backend/artifact.tar.gz
        dest: .
    - name: "Create top level directory for the unarchived files"
      file:
        path: ~/udapeople-backend
        state: directory
    - name: "Unarchive build artifact"
      unarchive:
        src: artifact.tar.gz
        dest: ~/udapeople-backend
    - name: "Install NPM dependencies and start backend app"
      shell: |
        cd ~/udapeople-backend
        npm install
        pm2 stop default
        pm2 start npm -- start