---
- name: "Create top level directory for the unarchived files"
  become: true
  file:
    path: ~/udapeople-backend
    state: directory
- name: "Unarchive build artifact"
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: ~/udapeople-backend
- name: "Install NPM dependencies and start backend app"
  become: true
  shell: |
    cd ~/udapeople-backend
    npm install
    pm2 stop default
    pm2 start npm -- start